env:
  node: true
  es2021: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: "tsconfig.json"
ignorePatterns: ["node_modules/**/*"]
plugins:
  - "@typescript-eslint"
root: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:eslint-comments/recommended"
  - "prettier"
rules:
  "@typescript-eslint/no-floating-promises":
    - error
    - ignoreIIFE: true
      ignoreVoid: true
  "@typescript-eslint/no-inferrable-types": "off"
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: _
      varsIgnorePattern: _
  "eslint-comments/no-unused-disable": "warn"
  no-unused-vars: "warn"
  no-extra-boolean-cast: "off"
  no-constant-condition: "off"
  no-async-promise-executor: "off"
  no-useless-escape: "warn"
